spring:
  application:
    name: chatop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatop
    username: ${USERNAME_POSTGRES}
    password: ${PASSWORD_POSTGRES}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 3001

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: true




