spring:
  application:
    name: chatop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatop
    username: ${USERNAME_POSTGRES}
    password: ${PASSWORD_POSTGRES}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

server:
  port: 3001
  base-url: http://localhost:3001


jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: true




